"use client";
import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import { CacheProvider } from "@chakra-ui/next-js";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CacheProvider>
        <ChakraProvider>
          <body >{children}</body>
        </ChakraProvider>
      </CacheProvider>
    </html>
  );
}
